        // src/utils/data.js
        export const products = [
        { 
            id: 1,
            name: "Pants",
            slug: "Pants",
            price: 450000,
            stock: 12,
            category: 1,
            category_name: "Electronics",
            rating: 4,
            img: "/images/pants.jpg",
        },
        {
            id: 2,
            name: "Hat",
            slug: "Hat",
            price: 650000,
            stock: 8,
            category: 1,
            category_name: "Electronics",
            rating: 5,
            img: "/images/hat.jpg",
        },
        {
            id: 3,
            name: "T-Shirt",
            slug: "t-shirt",
            price: 120000,
            stock: 20,
            category: 2,
            category_name: "Fashion",
            rating: 3,
            img: "/images/tshirt.jpg",
        },
        {
            id: 4,
            name: "Sneakers",
            slug: "sneakers",
            price: 350000,
            stock: 10,
            category: 2,
            category_name: "Fashion",
            rating: 5,
            img: "/images/sneakers.jpg",
        },
        ];
